apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true" # <1>
  name: backend-app
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      release: prometheus
  template:
    metadata:
      labels:
        app: backend
        release: prometheus
    spec:
      containers:
      - name: backend
        image: franroa/cloud-architechtures-3:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    app: backend
    release: prometheus
  ports:
    - port: 8081
      name: backend #This name will be used in the ServiceMonitor
      targetPort: 8080
      nodePort: 31166
  type: LoadBalancer